

const Usa = () => {
  return (
    <div>
      <h1>USA</h1>
      <p>The United States of America (USA), commonly known as the United States (U.S.) or America, is a country primarily located in North America. It is a federal union of 50 states and a federal capital district, Washington, D.C. The 48 contiguous states border Canada to the north and Mexico to the south, with the states of Alaska to the northwest and the archipelagic Hawaii in the Pacific Ocean. The United States also asserts sovereignty over five major island territories and various uninhabited islands.[j] The country has the world's third-largest land area,[d] largest exclusive economic zone, and third-largest population, exceeding 340 million.[k] Its three largest metropolitan areas are New York, Los Angeles, and Chicago, and its three most populous states are California, Texas, and Florida. <br/>
      Paleo-Indians migrated across the Bering land bridge more than 12,000 years ago, and formed various civilizations and societies. British colonization led to the first settlement of the Thirteen Colonies in Virginia in 1607, with the beginning of the forced migration of enslaved Africans following soon after. Clashes with the British Crown over taxation and political representation sparked the American Revolution, with the Second Continental Congress formally declaring independence on July 4, 1776. Following its victory in the 1775–1783 Revolutionary War, the country continued to expand westward across North America, resulting in the dispossession of native inhabitants. As more states were admitted, a North–South division over slavery led to the secession of the Confederate States of America, which fought states remaining in the Union in the 1861–1865 American Civil War. With the victory and preservation of the United States, slavery was abolished nationally. By 1900, the country had established itself as a great power, a status solidified after its involvement in World War I. After Japan's attack on Pearl Harbor in December 1941, the U.S. entered World War II. Its aftermath left the U.S. and the Soviet Union as the world's two superpowers and led to the Cold War, during which both countries struggled for ideological dominance and international influence. Following the Soviet Union's collapse and the end of the Cold War in 1991, the U.S. emerged as the world's sole superpower, wielding significant geopolitical influence globally.</p>
    </div>
  )
}

export default Usa